version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: loggy-postgres
    environment:
      POSTGRES_DB: loggy
      POSTGRES_USER: loggy
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - loggy_pgdata:/var/lib/postgresql/data

volumes:
  loggy_pgdata:

